name: Create Pull Request on Push

on:
  push:
    branches:
      - main  # Replace "main" with your desired branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: actions/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Pull Request: ${GITHUB_REF}"
          body: "This pull request automatically created on push."
          head: ${{ github.ref }}
          base: main  # Replace "main" with your desired base branch
